# These are supported funding model platforms
# Uncomment and customize as needed

# github: [username1, username2] # GitHub Sponsors usernames
# patreon: username # Patreon username  
# open_collective: projectname # Open Collective project name
# ko_fi: username # Ko-fi username
# custom: ['https://example.com'] # Custom sponsorship URLs 