# Repository metadata for GitHub
name: "bleuprint"
description: "🎯 Modern Mac development environment template with 120+ tools using Nix-Darwin. Security-first, reproducible, one-command setup."
homepage: "https://github.com/bleulabs/bleuprint"
topics:
  - "nix"
  - "nix-darwin"  
  - "macos"
  - "dotfiles"
  - "development-environment"
  - "template"
  - "cli-tools"
  - "rust"
  - "security"
  - "reproducible"
  - "homebrew"
  - "setup"
  - "bootstrap"
  - "modern-tools"
  - "developer-tools" 