name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          
    - name: Check Nix flake
      run: |
        nix flake check
        
    - name: Build configuration (dry-run)
      run: |
        nix build .#darwinConfigurations.testhost.system --dry-run
        
    - name: Check formatting
      run: |
        nix fmt -- --check
      continue-on-error: true  # Don't fail on format issues
      
    - name: Run shellcheck on scripts
      run: |
        brew install shellcheck
        shellcheck *.sh
      continue-on-error: true  # Warning only 